# Generated by Django 5.2.4 on 2026-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_id', models.CharField(max_length=50)),
                ('pile_type', models.CharField(max_length=20)),
                ('length', models.FloatField()),
                ('cutoff', models.FloatField()),
                ('cage_type', models.CharField(max_length=10)),
                ('stock_length', models.FloatField(default=12)),
                ('anchorage', models.FloatField(default=0.75)),
                ('total_length', models.FloatField(blank=True, null=True)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
