# Generated by Django 5.2.4 on 2026-03-29 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('concrete_grade', models.CharField(default='C35/45', max_length=20)),
                ('sand_content_limit_pct', models.FloatField(default=5.0, help_text='Max sand content % allowed before concreting')),
                ('viscosity_min_secs', models.FloatField(default=30.0)),
                ('viscosity_max_secs', models.FloatField(default=90.0)),
                ('density_min', models.FloatField(default=1.01)),
                ('density_max', models.FloatField(default=1.25)),
                ('volume_deviation_alert_pct', models.FloatField(default=15.0, help_text='Flag if actual concrete deviates from theoretical by this %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_no', models.CharField(max_length=50)),
                ('pile_type', models.CharField(choices=[('test', 'Test Pile'), ('working', 'Working Pile'), ('reaction', 'Reaction Pile')], default='working', max_length=20)),
                ('pile_diameter_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(3.0)])),
                ('design_depth_m', models.FloatField(help_text='Design total depth from ground level (m)', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('location_description', models.CharField(blank=True, help_text='e.g. B2 Area North, Grid C3', max_length=200)),
                ('rig_no', models.CharField(blank=True, max_length=20)),
                ('drawing_number', models.CharField(blank=True, max_length=100)),
                ('pile_coordinate', models.CharField(blank=True, max_length=100)),
                ('top_of_casing_m', models.FloatField(blank=True, null=True)),
                ('casing_installation_start', models.DateTimeField(blank=True, null=True)),
                ('casing_installation_end', models.DateTimeField(blank=True, null=True)),
                ('drilling_start', models.DateTimeField(blank=True, null=True)),
                ('drilling_end', models.DateTimeField(blank=True, null=True)),
                ('actual_depth_from_casing_m', models.FloatField(blank=True, null=True)),
                ('rebar_lowering_start', models.DateTimeField(blank=True, null=True)),
                ('rebar_lowering_end', models.DateTimeField(blank=True, null=True)),
                ('cover_blocks_fixed', models.BooleanField(default=False)),
                ('main_bars_spec', models.CharField(blank=True, help_text='e.g. 32mm', max_length=50)),
                ('stiffener_spec', models.CharField(blank=True, help_text='e.g. 2.25m spacing', max_length=50)),
                ('spiral_bars_spec', models.CharField(blank=True, help_text='e.g. 260mm @ 1/c', max_length=50)),
                ('flushing_start', models.DateTimeField(blank=True, null=True)),
                ('flushing_end', models.DateTimeField(blank=True, null=True)),
                ('inspection_collapse', models.BooleanField(blank=True, help_text='True=Collapse detected, False=No collapse', null=True)),
                ('casting_start', models.DateTimeField(blank=True, null=True)),
                ('casting_end', models.DateTimeField(blank=True, null=True)),
                ('actual_concrete_m3', models.FloatField(blank=True, null=True)),
                ('concrete_slump_mm', models.IntegerField(blank=True, null=True)),
                ('rough_sheet_photo', models.ImageField(blank=True, help_text='Photo of handwritten rough sheet — audit proof', null=True, upload_to='rough_sheets/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piles_recorded', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piles', to='piling.pilingproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'pile_no')},
            },
        ),
        migrations.CreateModel(
            name='SlurryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initial', 'Initial (pre-drilling)'), ('final', 'Final (pre-concreting)')], max_length=10)),
                ('checked_at', models.DateTimeField()),
                ('viscosity_secs', models.FloatField(help_text='Marsh funnel viscosity in seconds')),
                ('specific_gravity', models.FloatField(help_text='Density / specific gravity reading', validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(2.0)])),
                ('sand_content_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ph_value', models.FloatField(blank=True, null=True)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slurry_checks', to='piling.pile')),
            ],
            options={
                'ordering': ['pile', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('depth_to_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('texture', models.CharField(choices=[('normal_sand', 'Normal sand'), ('slightly_mud', 'Slightly mud'), ('soft_mud', 'Soft mud'), ('strong_mud', 'Strong mud'), ('brown_clay', 'Brown clay'), ('brown_sharp_sand', 'Brown sharp sand'), ('grey_sharp_sand', 'Grey sharp sand'), ('strong_clay', 'Strong clay'), ('rock', 'Rock'), ('other', 'Other')], max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_layers', to='piling.pile')),
            ],
            options={
                'ordering': ['depth_from_m'],
            },
        ),
        migrations.CreateModel(
            name='TremieSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('length_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(20.0)])),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tremie_sequences', to='piling.pile')),
            ],
            options={
                'ordering': ['sequence_no'],
                'unique_together': {('pile', 'sequence_no')},
            },
        ),
    ]
