# Generated by Django 5.2.4 on 2026-04-30 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piling', '0002_reinforcement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='actual_depth_from_casing_m',
            field=models.FloatField(blank=True, help_text='Measured actual pile depth from casing top (m)', null=True),
        ),
        migrations.AlterField(
            model_name='pile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pile',
            name='location_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pile',
            name='main_bar_dia_mm',
            field=models.FloatField(blank=True, help_text='Main bar diameter in mm (e.g. 32)', null=True, validators=[django.core.validators.MinValueValidator(6.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='pile',
            name='spiral_pitch_m',
            field=models.FloatField(blank=True, help_text='Spiral ring centre-to-centre pitch (m)', null=True, validators=[django.core.validators.MinValueValidator(0.05)]),
        ),
        migrations.AlterField(
            model_name='pile',
            name='stiffener_spacing_m',
            field=models.FloatField(blank=True, help_text='Stiffener ring centre-to-centre spacing (m)', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='slurrycheck',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slurrycheck',
            name='specific_gravity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='slurrycheck',
            name='viscosity_secs',
            field=models.FloatField(),
        ),
    ]
